"""Stable process exit codes for the Pipe CLI."""

SUCCESS = 0
USAGE_ERROR = 2
PROJECT_ROOT_NOT_FOUND = 3
INPUT_UNAVAILABLE = 4
INPUT_INVALID_JSON = 5
BASELINE_INVALID = 6
INTERNAL_CONTRACT_ERROR = 7
MANIFEST_INVALID = 8
READINESS_BLOCKED = 9
